Send review
a-jaxell/LuleApi pull request #1
Opened 2023-02-05 06:30 UTC by Rasmus3liasson

Skickar formuläret på movie sidan till cms:et.
Ingen super styling men tänker att vi väntar in tills vi har all data på plats för att få det att se bra ut.

2023-02-09 06:31 UTC, a-jaxell commented on server/server.js
> +  );
Vad innebär %5B / %5D här ?
Är det ersättning för specialtecken?

2023-02-09 06:51 UTC, Rasmus3liasson commented on server/server.js
> +  );
Använde samma url strukturen som var i dokumentationen från swagger.

I detta fall hade man lika gärna kunnat filtrera samma resultet med `https://plankton-app-xhkom.ondigitalocean.app/api/reviews?filters[movie]=${movieID}`

2023-02-09 07:26 UTC, a-jaxell requested changes
Snyggt jobbat! 

Jag tänker dock att det skulle vara nice att ha serverlogiken i en separat fil och exportera den till server.js för att separera delarna. 

Jag använde mig av express.Router() i min del.

2023-02-09 08:26 UTC, Rkron91 requested changes
mer separation of concern önskas, det kommer att bli svårt att testa dessa funktioner. 
bör läggas i en separat fil & funktion och importeras till server.js

2023-02-09 09:24 UTC, Rasmus3liasson commented
Kolla om ändringarna ser okej ut eller om det ngt som bör ändras?

2023-02-09 09:28 UTC, a-jaxell approved these changes
Grymt! Ser bra ut :)

2023-02-09 10:14 UTC, Rkron91 approved these changes
Snyggt! 

dock så hade inte routen behövt flyttats ur servern, men det är mitt fel för att jag var otydlig :)

                                                                                                    --> funktion för filtrering
rent visuelt så tänker jag såhär : Frontend fetch --> /serverRoute --> funktion fetch cms

2023-02-09 10:25 UTC, Rkron91 requested changes
Såg nu att funktionerna inte har någon export, dvs dem kan ej importeras till testmiljö, 

och serverRouten kan flyttas tillbaka till server.js, men gör logiken dvs, fetch från cms apit i en separat fil och gärna filtreringen / behandlingen av datan i en separat som du importerar till server.js

2023-02-10 08:53 UTC, Rkron91 approved these changes
Provat och funktionen är approved!

2023-02-10 08:59 UTC, merged

2023-02-11 19:58 UTC, burrozd commented
Provade och den fungerar som den ska