Omdb rating
a-jaxell/LuleApi pull request #7
Opened 2023-02-11 12:49 UTC by burrozd

Function that gets rating of movie from OMDb-API if there are less than 5 reviews on a movie.

2023-02-11 14:10 UTC, Rkron91 requested changes
Massa formateringsändringar, Formatera koden med Prettier! detta bestämde vi att vi skulle göra i början. 
det gäller följande filer: server/rating.js,  server/server.js, views/movies.ejs, 

sen undrar jag vad  `"dependencies": "^0.0.1",`  är för något som är tillagdt i package.json?

2023-02-11 19:11 UTC, burrozd commented
> Massa formateringsändringar, Formatera koden med Prettier! detta bestämde vi att vi skulle göra i början. det gäller följande filer: server/rating.js, server/server.js, views/movies.ejs,
> 
> sen undrar jag vad `"dependencies": "^0.0.1",` är för något som är tillagdt i package.json?

Jag har använt mig utav prettier hela tiden. 
"dependencies": "^0.0.1" kom med när jag körde npm install dependencies.
@Rkron91

2023-02-12 10:32 UTC, Rkron91 commented
> > Massa formateringsändringar, Formatera koden med Prettier! detta bestämde vi att vi skulle göra i början. det gäller följande filer: server/rating.js, server/server.js, views/movies.ejs,
> > sen undrar jag vad `"dependencies": "^0.0.1",` är för något som är tillagdt i package.json?
> 
> Jag har använt mig utav prettier hela tiden. "dependencies": "^0.0.1" kom med när jag körde npm install dependencies. @Rkron91

okok! knepigt, om du kollar denna pullrequest, tryck på "Files changed" och kolla igenom det.
så ser du att det är många ändringar som bara är typ indenteringar. 

dem är inte nödvändiga ändringar och gör pullrequesten mycket svåröverskådlig då det tar mycket längre tid att försöka hitta var den "riktiga" ändringen/tillägget ligger. 

så vore bra om du kunde försöka kolla upp varför det blir så och försöka åtgärda det!

och angående `npm install dependencies` vad var det du ville ha för effekt av det? :) 
jag **tror** att det räcker med att bara skriva npm install? 

du får gärna förklara npm install dependencies annars, kan mycket väl vara något jag inte vet med :)

2023-02-12 11:29 UTC, Rkron91 commented
> > > Massa formateringsändringar, Formatera koden med Prettier! detta bestämde vi att vi skulle göra i början. det gäller följande filer: server/rating.js, server/server.js, views/movies.ejs,
> > > sen undrar jag vad `"dependencies": "^0.0.1",` är för något som är tillagdt i package.json?
> > 
> > 
> > Jag har använt mig utav prettier hela tiden. "dependencies": "^0.0.1" kom med när jag körde npm install dependencies. @Rkron91
> 
> okok! knepigt, om du kollar denna pullrequest, tryck på "Files changed" och kolla igenom det. så ser du att det är många ändringar som bara är typ indenteringar.
> 
> dem är inte nödvändiga ändringar och gör pullrequesten mycket svåröverskådlig då det tar mycket längre tid att försöka hitta var den "riktiga" ändringen/tillägget ligger.
> 
> så vore bra om du kunde försöka kolla upp varför det blir så och försöka åtgärda det!
> 
> och angående `npm install dependencies` vad var det du ville ha för effekt av det? :) jag **tror** att det räcker med att bara skriva npm install?
> 
> du får gärna förklara npm install dependencies annars, kan mycket väl vara något jag inte vet med :)

jag noterade även att din pullrequest vill lägga till saker som vi plockat bort från sprint-1. 
så det du skulle behöva göra är att

2023-02-12 13:59 UTC, burrozd commented
> > > Massa formateringsändringar, Formatera koden med Prettier! detta bestämde vi att vi skulle göra i början. det gäller följande filer: server/rating.js, server/server.js, views/movies.ejs,
> > > sen undrar jag vad `"dependencies": "^0.0.1",` är för något som är tillagdt i package.json?
> > 
> > 
> > Jag har använt mig utav prettier hela tiden. "dependencies": "^0.0.1" kom med när jag körde npm install dependencies. @Rkron91
> 
> okok! knepigt, om du kollar denna pullrequest, tryck på "Files changed" och kolla igenom det. så ser du att det är många ändringar som bara är typ indenteringar.
> 
> dem är inte nödvändiga ändringar och gör pullrequesten mycket svåröverskådlig då det tar mycket längre tid att försöka hitta var den "riktiga" ändringen/tillägget ligger.
> 
> så vore bra om du kunde försöka kolla upp varför det blir så och försöka åtgärda det!
> 
> och angående `npm install dependencies` vad var det du ville ha för effekt av det? :) jag **tror** att det räcker med att bara skriva npm install?
> 
> du får gärna förklara npm install dependencies annars, kan mycket väl vara något jag inte vet med :)

Jag försöker att fixa indenteringarna, har avinstallerat prettier samt alla andra extensions som jag har, men min vs code ändrar automatiskt indenteringar.
Jag fortsätter återigen att hitta problemet med formateringen, annars får jag avinstallera och installera om vs code i värsta fall..

Det kanske hade räckt med `npm install` istället för `npm install dependencies`

2023-02-13 18:47 UTC, closed without merging